#+TITLE: Curso de Business Intelligence: Utilidad y Áreas de oportunidad

* Fundamentos
** Introducción
- =Business Intelligence (BI)= vs =Data Science (DS)=
  - =BI= es un análisis descriptivo y situacional del presente:
    - Qué está pasando? Qué estuvo pasando?
  - =DS= puede ir más allá por ejemplo, con modelos predicativos:
    - Hacia donde vamos?

-----

- Procesos del =BI=
  - =ETL=
    - =Extract=:
      - Recopilar información que podamos de la manera que sea necesaria.
    - =Transform=:
      - Limpieza de la información porque no siempre esta estructurada, organizada o sin errores.
    - =Load=:
      - Continuar con el proceso porque la intención es subir esta a algún software para analizarla.
  - Exploración:
    - Es la etapa más larga, estar indagando en la data, que ocurre según los datos.
  - Descubrimientos:
    - Fue lo encontrado, que hay de interesante, que patrones?
  - =Reporting=:
    - Entregar el mensaje de lo obtenido con los datos.
- Presentar La información:
  - Visualización de datos:
    - La manera en la que presentamos la información de manera visual.
  - =Story telling=:
    - Manera en la que se narran los descubrimientos para cautivar a la audiencia.


** Qué es =stakeholders=
- También llamados grupos de intereses.
- Son personas que tienen algún interés en la compañía.
  - Y que pueden afectar o ser afectados por esta.
  - Algunos comunes pueden ser:
    - Primarios:
      - Accionistas.
      - Clientes.
      - Proveedores.
      - Empleados.
    - Secundarios:
      - Sociedad.
      - Gobierno.
      - Comerciantes.
  - Pueden ser internos o externos a la organización

-------

- Tenemos que pensar en los intereses de los =stakeholders= que tengan mayor prioridad.
  - Para esto debemos de entender sus intereses.
    - Accionistas:
      - Retorno de inversión.
    - Clientes:
      - Calidad de productos, servicios y necesidades.
    - Empleados:
      - Seguridad y estabilidad.
    - Proveedores:
      - Estabilidad e ingresos.

--------

- Debemos priorizar a los nuestros y a los más importantes.
  - Depende de la organización.
    - Ejemplos:
      - Empresa tradicional:
        - Accionistas.
        - Clientes.
        - Empleados.
      - Una =Startup=:
        - Clientes.
        - Empleados.
        - Accionistas.
  - Básicamente debemos salvaguardar los intereses de los =stakeholders=.

** Tipos de empresa: venta de productos o servicios
- Es importante diferenciarlos para entender la afectación de cada una en el estado de resultados.
- Estado de resultados (EDR):
  - Es un documento.
  - Tiene las pautas de como funcionan las utilidades de la empresa.
  - *Utilidad Bruta* =  ingresos - Costos de venta.
  - *Utilidad Operativa* = Utilidad Bruta - Gastos de administración.
  - *Utilidad Neta* = Utilidad Operativa - Otras gastos e impuestos - Impuestos.
    - Es la más importante.
- EDR según el tipo de empresa:
  - Productos:
    - En general las ventas menos los costos de producción.
  - Servicios:
    - Generalmente los gastos están en la nómina, gastos administrativos, etc.

** =Income statement= simplificado: utilidad bruta, operativa y neta
- =Income statement= = Estado de resultados
- Siempre es recomendado ir de los particular a lo general.
  - Tomar una actividad y llevarla al =income statement=.
- Utilidad Bruta:
  - Si es negativa, deberíamos arreglarlo inmediatamente ya que estamos perdiendo dinero.
- Utilidad operativa:
  - Su relación con la utilidad bruta nos permite descubrir gastos excesivos y recortarlos.
- Cómo afecta cada actividad al =income statement=?
  - Costo en materia prima.
  - Incremento en nómina.
  - Cambio de oficinas.
  - etc.

** Ingreso, utilidad y costos
- Utilidad vs ingresos:
  - Un ingreso (revenue) es todo aquello a lo que no se le ha sustraído los gastos.
    - Mayor ingreso, no implica mayor utilidad (ej. descuentos).
    - Mayor costo no siempre implica menor utilidad (ej. gasto de marketing).
- Costos:
  - *Costo fijo*:
    - Ocurren de manera periódica, como la renta de oficinas.
  - *Costo variable:*
    - Están relacionados a una actividad, en donde mayor actividad, mayor costo.
    - Como con las ventas.
  - *Costo semivariable*:
    - Es fijo hasta cierto punto y luego variable.
    - Como el costo de la electricidad.
  - Mayores costos no significan siempre menor utilidad.

** Margen de contribución
- Es la diferencia entre el precio de mis productos menos el costo del producto
- Nos ayuda a encontrar nuestro punto de equilibrio.
  - El punto en donde no tenemos ni ganancias ni perdidas.

$PE = \frac {\textrm{Costos fijos}} {\textrm{Precio de venta} - \textrm{costo variable por unidad}}$

** Razones matemáticas en los negocios
- aaa
